#!/usr/bin/env python
# -*- coding: utf-8 -*-

####
#CI3725 - Etapa 1 - Analisis Lexicografico
#Fabio, Castro, 10-10132
#Antonio, Scaramazza 11-10957
####

import ply.lex as lex

# Reserverd words of the language
reserved = {
    # language
    'program' : 'Program',

    # types
    'int' : 'Int',
    'bool' : 'Bool',
    'set' : 'Set',

    ## values
    'true' : 'True',
    'false' : 'False',

    # instructions
    'using' : 'Using',
    'in' : 'In',

    ## conditionals
    'if' : 'If',
    'then' : 'Then',
    'else' : 'Else',

    ## loops
    'repeat' : 'Repeat',
    'while' : 'While',

    'do': 'Do',

    'for' : 'For',

    ## in/out
    'scan' : 'Scan',

    'print' : 'Print',
    'println' : 'PrintLn',

    # expressions/operators
    'or' : 'Or',
    'and' : 'And',
    'not' : 'Not',

    ## functions
    'def' : 'Def',
    'return': 'Return'
}

# Tokens to be recognized
tokens = [
    # Language
    'Number',
    'Comma',
    'SemiColon',
    'Assign',

    # Identifiers
    'ID',

    # Instructions
    'Arrow',
    'String',

    # Expressions/Operators
        # Set Operators
            'SetPlus',
            'SetMinus',
            'SetTimes',
            'SetMod',
            'SetDivition',
            'SetMax',
            'SetMin',
            'SetLen',
            'SetIntersection',
            'SetUnion',
            'SetDifference',
        # Int Operators
            'Plus',
            'Minus',
            'Times',
            'Divide',
            'Module',
        #  Bool Operators
            'Less',
            'LessEq',
            'Great',
            'GreatEq',
            'Equal',
            'UnEqual',
            # set-bool operators
                'SetBelong',   
        #  bracket
           'OpenParen',
           'CloseParen',
           'OpenCurly',
           'CloseCurly'
] + list(reserved.values())

# Returns the actual value in Python's int type
def t_Number(t):
    r'\d+'
    t.value = int(t.value)
    return t

t_Comma = r','
t_SemiColon = r';'
t_Assign = r'='

def t_ID(t):
    r'\w[\w\d]*'
    # If there are no reserved words that match, it's an ID
    t.type = reserved.get(t.value, 'ID')
    return t

t_Arrow = r'->'
# These Strings take input even after new lines, it ends only and only in ' " '
# t_STRING = r'"[^"]*"'

# These Strings take input until a " is found (in the same line),
# if there's a new line it reports an error.
##########
# The ? in the regular expression indicates non-greedy matching,
# for cases like:
#   writeln "number ", N, " is even"
# where it should recognize 6 separate tokens:
#   ['writeln', '"number "', ',', 'N', ',', '" is even"']
# not 2 tokens:
#   ['writeln', '"number ", N, " is even"']
# being the latter one a String
##########
t_String = r'".*?"'

# set token
t_SetPlus = r'\<\+\>'
t_SetMinus = r'\<\-\>'
t_SetTimes = r'\<\*\>'
t_SetDivition = r'\<\/\>'
t_SetMod = r'\<\%\>'
t_SetMax = r'\>\?'
t_SetMin = r'\<\?'
t_SetLen = r'\$\?'
t_SetIntersection = r'\>\<'
t_SetUnion = r'\+\+'
t_SetDifference = r'\\'

# int token
t_Plus = r'\+'
t_Minus = r'-'
t_Times = r'\*'
t_Divide = r'/'
t_Module = r'%'

# bool token
t_Less = r'\<'
t_LessEq = r'\<\='
t_Great = r'\>'
t_GreatEq = r'\>\='
t_Equal = r'\=\='
t_UnEqual = r'\/\='

#set-bool token
t_SetBelong = r'\@'

# brackets
t_OpenParen = r'\('
t_CloseParen = r'\)'
t_OpenCurly = r'\{'
t_CloseCurly = r'\}'

# Ignores spaces, tabs and (C style) comments
t_ignore = " \t"
t_ignore_COMMENT = r'\#.*'

# The only new line character considered is '\n'
def t_newline(t):
    r'\n+'
    t.lexer.lineno += t.value.count('\n')

# To find the column number of the current line
def find_column(text,token):
    last_cr = text.rfind('\n',0,token.lexpos)
    if last_cr < 0:
        last_cr = -1
    column = token.lexpos - last_cr
    return column

# Error to be shown if the lexer finds an "Unexpected" character in the program
def t_error(t):
    errors_list.append("ERROR: Unexpected character '%s' at line %d, column %d"
                       % (t.value[0], t.lineno, find_column(lexer.lexdata, t)))
    t.lexer.skip(1)

# The file (represented in a Python String)
# goes through the lexer and returns the list of tokens
def lexing(file):

    global errors_list, lexer

    lexer = lex.lex()
    tokens_list = []
    errors_list = []

    lexer.input(file)

    # Pass entire file through lexer
    for tok in lexer:
        tokens_list.append(tok)

    # If no "Unexpected character" was found
    if not errors_list:
        return tokens_list
    else:
        # Print all the "Unexpected character" errors
        for error in errors_list:
            print error

        # Empty list to indicate error
        return []

###############################################################################

# Only to be called if this is the main module (not imported in another one)
def main(argv = None):
    import sys    # argv, exit

    if argv is None:
        argv = sys.argv

    if len(argv) == 1:
        print "ERROR: No input file"
        sys.exit() ## return (averiguar cuál es mejor)
    elif len(argv) > 2:
        print "ERROR: Invalid number of arguments"
        sys.exit() ## return (averiguar cuál es mejor)

    # Opens file to interpret
    file = open(argv[1], 'r')

    # Reads the file and passes it to the Lexer
    tokens_list = lexing(file.read())

    for tok in tokens_list:
        print 'Token' + str(tok.type),
        if str(tok.type) == 'ID':
            print ': "' + tok.value + '"',
        elif str(tok.type) == 'String':
            print ': ' + tok.value,
        print '(Línea ' + str(tok.lineno) + ',',
        print 'Columna ' + str(find_column(lexer.lexdata, tok)) + ')'

# If this is the module running
if __name__ == "__main__":
    main()